version: '{build}'

branches:
  except:
    - gh-pages

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

platform:
  - x86

configuration:
  - Debug
  - Release

after_build:
  - 7z a bbmod.zip %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\dinput8.dll %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\dinput8.pdb %APPVEYOR_BUILD_FOLDER%\README.md addons

artifacts:
  - path: bbmod.zip
