version: '{build}'

branches:
  except:
    - gh-pages

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

platform:
  - x86

configuration:
  - Debug
  - Release

after_build:
  - ps: ci/after_build.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: udfK+NwCNkCuD5KHX3lxRF9XHQLxEqtRPdpq2vihJr5W6iRuxbBbrgW5dpd5tO2O
  description: ''
  draft: true
  on:
    CONFIGURATION: Release
    appveyor_repo_tag: true
  provider: GitHub
